CREATE DATABASE IF NOT EXIST VideogameDatabase;

USE VideogameDatabase;

CREATE TABLE Plataforma(
  Plataform_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_de_la_plataforma VAR CHAR(50) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Launcher(
  LAUNCHER_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Launcher VAR CHAR(50) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Usuario(
  Usuario_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Usuario VAR CHAR(50) NOT NULL,
  Edad VAR CHAR(3) NOT NULL,
  Telefono VAR CHAR(10) NOT NULL,
  Correo_electrónico VAR CHAR(50) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Juego(
  Juego_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Juego VAR CHAR(50) NOT NULL,
  Precio VAR CHAR(50) NOT NULL,
  Genero VAR CHAR(30) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE UsuariosXJuego(
  UsuariosXJuego_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Usuario_ID INTEGER UNSIGNED,
  Juego_ID INTEGER UNSIGNED,
  FOREIGN KEY(Usuario_ID)
    REFERENCES Usuario(Usuario_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(Juego_ID)
    REFERENCES Juego(Juego_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE JuegoXPlataformaXLauncher(
  JuegoXPlataformaXLauncher_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Juego_ID INTEGER UNSIGNED,
  Plataform_ID INTEGER UNSIGNED,
  LAUNCHER_ID INTEGER UNSIGNED,
  FOREIGN KEY(Juego_ID)
    REFERENCES Juego(Juego_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(Plataform_ID)
    REFERENCES Plataform(Plataform_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(LAUNCHER_ID)
    REFERENCES Launcher(LAUNCHER_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;