CREATE DATABASE IF NOT EXIST VideogameDatabase;

USE VideogameDatabase;

CREATE TABLE Usuario(
  Usuario_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Usuario VARCHAR(30) UNIQUE NOT NULL,
  Edad VARCHAR(3) NOT NULL,
  Telefono VARCHAR(10) NOT NULL,
  Correo_electrónico VARCHAR(50) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Juego(
  Juego_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Juego VARCHAR(50) UNIQUE NOT NULL,
  Genero VARCHAR(50) NOT NULL,
  Precio FLOAT(2) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Plataforma(
  Plataform_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_de_la_plataforma VARCHAR(30) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Launcher(
  LAUNCHER_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre_del_Launcher VARCHAR(30) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE UsuariosXJuego(
  UsuariosXJuego_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Usuario_ID INTEGER UNSIGNED,
  Juego_ID INTEGER UNSIGNED,
  FOREIGN KEY(Usuario_ID)
    REFERENCES Usuario(Usuario_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(Juego_ID)
    REFERENCES Juego(Juego_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE JuegoXPlataformaXLauncher(
  JuegoXPlataformaXLauncher_ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Juego_ID INTEGER UNSIGNED,
  Plataform_ID INTEGER UNSIGNED,
  LAUNCHER_ID INTEGER UNSIGNED,
  FOREIGN KEY(Juego_ID)
    REFERENCES Juego(Juego_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(Plataform_ID)
    REFERENCES Plataforma(Plataform_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  FOREIGN KEY(LAUNCHER_ID)
    REFERENCES Launcher(LAUNCHER_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;